title: Dr. Zhiwei WANG
url: "https://andysis.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://andysis.github.io/"
footer_text: "Be kind, for everyone's fighting a hard battel."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Publication"
   link: "publication"
 - name: "Resume"
   link: "resume.pdf"
